name: Linux Desktop Build
run-name: Building P2Pirate for Linux 🐧

on:
  pull_request:
    branches: [main, cheetah, cheetahdex, fix/*, add/*, release/*, hotfix/*, feature/*]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build_desktop:
    name: Build Desktop (linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Flutter and dependencies
        id: install_flutter
        uses: ./.github/actions/flutter-deps

      - name: Setup Linux environment
        id: setup_linux
        uses: ./.github/actions/releases/setup-linux
        with:
          gpg-key: ${{ secrets.LINUX_GPG_KEY }}
          gpg-key-id: ${{ secrets.LINUX_GPG_KEY_ID }}

      - name: Fetch packages, generate assets, and build for Linux
        id: build
        env:
          GITHUB_API_PUBLIC_READONLY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./.github/actions/generate-assets
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }}
          FEEDBACK_API_KEY: ${{ secrets.FEEDBACK_API_KEY }}
          FEEDBACK_PRODUCTION_URL: ${{ secrets.FEEDBACK_PRODUCTION_URL }}
          MATOMO_URL: ${{ secrets.MATOMO_URL }}
          MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID }}
          BUILD_COMMAND: flutter build linux --no-pub --release

      - name: Test Linux desktop UI
        if: ${{ github.event_name == 'pull_request' }}
        run: dart run_integration_tests.dart

      - name: Compute short commit SHA
        id: vars
        shell: bash
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/linux/x64/release/bundle/*
          name: p2pirate-linux-${{ steps.vars.outputs.short_sha }}.zip
          retention-days: 5
