# Rule for running static analysis and code formatting checks on all PRs
# Runs static analysis and code formatting checks on all PRs to ensure the codebase is clean and consistent
name: Validate Code Guidelines
run-name: ${{ github.actor }} is validating code guidelines 🚀

on:
  pull_request:
    branches:
      - "*"

jobs:
  validate_code_guidelines:
    runs-on: ubuntu-latest

    steps:
      - name: Setup GH Actions
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Flutter and dependencies
        id: install_flutter
        uses: ./.github/actions/flutter-deps

      - name: Resolve packages
        run: flutter pub get --enforce-lockfile

      - name: Resolve SDK workspace dependencies
        id: sdk_pub_get
        run: |
          if [ -f sdk/pubspec.lock ]; then
            dart pub get --enforce-lockfile -C sdk
          else
            dart pub get -C sdk
          fi

      - name: Validate dart code
        id: validate_dart
        run: |
          flutter analyze --no-fatal-warnings --no-fatal-infos
          # Currently skipped due to many changes. Will be enabled in the future after doing full sweep of the codebase
          # dart format --set-exit-if-changed .
